version: '3.7'

services:

  survey:
    container_name: survey
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5201:5200'
